module Antlr4ruby

  class AmbiguityInfo < DecisionEventInfo
    attr_accessor ambig_alts: BitSet

    def initialize: (Integer, ATNConfigSet, BitSet, _TokenStream, Integer, Integer, bool) -> void
  end
end
