

module Antlr4ruby
  module Misc
    class Interval
      INTERVAL_POOL_MAX_VALUE: Integer
      INVALID: Interval
      # @@cache: Array[Interval]

      @a: Integer
      @b: Integer

      # @@cache: Array[Interval]

      def initialize: (Integer, Integer) -> void

      def self.of: (Integer, Integer) -> Interval

      def length: -> Integer

      def starts_before_disjoint: (Interval) -> bool

      def starts_before_non_disjoint: (Interval) -> bool

      def starts_after:(Interval) -> bool

      def starts_after_disjoint: (Interval) -> bool

      def starts_after_non_disjoint:(Interval) -> bool

      def disjoint: (Interval) -> bool

      def adjacent:(Interval) -> bool

      def properly_contains:(Interval) -> bool

      def union:(Interval) -> Interval
      def intersection: (Interval) -> Interval

      def difference_not_properly_contained: (Interval) -> Interval
    end
  end
end

