module Antlr4ruby
  class MurmurHash
    DEFAULT_SEED: Integer

    def self.finish: (Integer, Integer) -> Integer

    def self.init: (Integer) -> Integer

    def self.update: (Integer, Object) -> Integer

    def self.hash: (Array[untyped], Integer) -> untyped
  end
end
