

module Antlr4ruby
  module Misc
    class Pair[A, B]

      attr_accessor first: A
      attr_accessor second: B

      @first: A
      @second: B

      def initialize: (A, B) -> void

    end
  end
end

