# 已完成

module Antlr4ruby
  interface _ANTLRErrorListener
    def syntax_error: (
        Recognizer[untyped, untyped], Object, Integer, Integer, String, RecognitionException
      ) -> void

    # 后面这些看情况取舍
    def report_ambiguity: (
        Parser, DFA, Integer, Integer, bool, BitSet, ATNConfigSet
      ) -> void

    def report_attempting_full_context: (
        Parser, DFA, Integer, Integer, BitSet, ATNConfigSet
      ) -> void

    def report_context_sensitivity: (
        Parser, DFA, Integer, Integer, Integer, ATNConfigSet
      ) -> void
  end
end

