
module Antlr4ruby
  class CharStreams
    DEFAULT_BUFFER_SIZE: Integer

    def self.from_file: (File, String?) -> _CharStream

    def self.from_file_name: (String, String?) -> _CharStream

    def self.from_path: (String, String?) -> _CharStream

    def self.from_string: (String, String) -> CodePointCharStream
  end
end