
module Antlr4ruby
  class CommonTokenStream < BufferedTokenStream
    attr_accessor channel: Integer
    def initialize: (_TokenSource, Integer) -> void

    def get_number_of_on_channel_tokens: -> Integer
  end
end