
module Antlr4ruby
  class CommonToken
    include _Token

    @type: Integer
    @line: Integer
    @char_position_in_line: Integer
    @channel: Integer
    @text: String
    @index: Integer
    @start: Integer
    @stop: Integer
    @source: Pair[_TokenSource, _CharStream]
    EMPTY_SOURCE: Pair[_TokenSource, _CharStream]

    attr_accessor channel: Integer
    attr_accessor char_position_in_line: Integer
    attr_accessor index: Integer
    attr_accessor line: Integer
    attr_accessor source: Pair[_TokenSource, _CharStream]
    attr_accessor start: Integer
    attr_accessor stop: Integer
    attr_accessor text: String
    attr_accessor type: Integer

    def initialize: (type: Integer?, source: Pair[_TokenSource, _CharStream]?, channel: Integer?, start: Integer?, stop: Integer?, text: String?, old_token: _Token?) -> void

    def set_start_index: (Integer) -> void

    def set_stop_index: (Integer) -> void

    def to_s: (Recognizer[untyped, untyped]?) -> String
  end
end