
module Antlr4ruby
  class DiagnosticErrorListener < BaseErrorListener
    attr_reader exact_only: bool

    def get_conflicting_alts: (BitSet, ATNConfigSet) -> BitSet

    def get_decision_description: (Parser, DFA) -> String
  end
end