
module Antlr4ruby
  class NoViableAltException < RecognitionException
    attr_reader start_token: _Token
    attr_reader dead_end_configs: ATN::ATNConfigSet?

    def initialize: (Parser, _TokenStream?, _Token?, _Token?, ATN::ATNConfigSet?, ParserRuleContext?) -> void

    def get_dead_end_configs: -> ATN::ATNConfigSet

    def get_start_token: -> _Token

  end
end