

module Antlr4ruby
  interface _TokenFactory[T]

    # 改成关键字参数
    def create: (type: Integer, text: String, source: Pair[_TokenSource, _CharStream]?,
      channel: Integer?, start: Integer?, stop: Integer?, line: Integer?, position:Integer?) -> T
  end
end