
module Antlr4ruby
  interface _TokenStream
    include _IntStream

    def lt: (Integer) -> _Token
    def get: (Integer) -> _Token
    def get_token_source: -> _TokenSource

    # 修改为关键字参数
    def get_text:(rule_context: RuleContext?, interval: Interval?, start: _Token?, stop: _Token?) -> String
  end
end