
# module Antlr4ruby
#   interface _WritableToken
#     # include _Token
#
#     def set_text: (String) -> void
#     def set_type: (Integer) -> void
#     def set_line: (Integer) -> void
#     def set_char_position_in_line: (Integer) -> void
#     def set_channel: (Integer) -> void
#     def set_token_index: (Integer) -> void
#   end
# end