
module Antlr4ruby
  # todo 继承运行时异常
  class RecognitionException
    attr_reader ctx: RuleContext

    attr_reader input: _IntStream
    attr_accessor offending_state: Integer
    attr_accessor offending_token: _Token
    attr_reader recognizer: Recognizer[untyped, untyped]

    def initialize: (Recognizer[untyped, untyped], _IntStream, ParserRuleContext?, String) -> void

    def get_ctx: -> RuleContext

    def get_expected_tokens: -> RangeSet[Integer]

    def get_input_stream: -> _IntStream

    def get_offending_state: -> Integer

    def get_offending_token: -> _Token

    def get_recognizer: -> Recognizer[untyped, untyped]

    def set_offending_state: (Integer) -> void

    def set_offending_token: (_Token) -> void
  end
end