module Antlr4ruby

  class DFA
    # @states: Hash[DFAState, DFAState]
    # @decision: Integer
    # @atn_start_state: DecisionState

    # @precedence_dfa: bool

    attr_reader atn_start_state: DecisionState
    attr_reader decision: Integer
    attr_reader precedence_dfa: bool
    attr_accessor s0: DFAState?
    attr_reader states: Hash[DFAState, DFAState]

    def initialize: (DecisionState, Integer) -> void

    def get_precedence_start_state: (Integer) -> DFAState

    def get_states: -> Array[DFAState]

    def is_precedence_dfa: -> bool

    def set_precedence_start_state: (Integer, DFAState) -> void

    def to_lexer_string: -> String

    def to_s: (Vocabulary?) -> String
  end
end

