module Antlr4ruby

  class DFASerializer
    @dfa: DFA
    @vocabulary: Vocabulary

    attr_reader dfa: DFA

    attr_reader vocabulary: Vocabulary

    def get_edge_label: (Integer) -> String

    def get_state_string: (DFAState) -> String
  end
end
