module Antlr4ruby

  class LexerActionExecutor
    def self.append: (LexerActionExecutor, _LexerAction) -> LexerActionExecutor

    attr_reader hash_code: Integer

    def initialize: (Array[_LexerAction]) -> void

    def execute: (Lexer, _CharStream, Integer) -> void

    def fix_offset_before_match: (Integer) -> LexerActionExecutor

    def get_lexer_actions: -> Array[_LexerAction]

    # def execute: () -> void

    private

    attr_reader lexer_actions: Array[_LexerAction]
  end
end
